server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # 🔴 /dev/ 경로 지원
    location /dev/ {
        try_files $uri $uri/ /dev/index.html;
    }

    # 루트 경로 지원
    location / {
        try_files $uri $uri/ /index.html;
    }
}
