server {
    listen 80;

    # 🔴 /dev/ 경로에 대한 요청 처리 추가
    location /dev/ {
        alias  /usr/share/nginx/html/;
        index  index.html index.htm;
        try_files $uri $uri/ /dev/index.html;
    }

    # 기본 루트 경로
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
